apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
               name: wordpressdb-configurations
               key: dbhost
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
                name: wordpressdb-configurations
                key: dbuser
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
                name: wordpressdb-configurations
                key: dbpassword
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
                 name: wordpressdb-configurations
                 key: dbname

